version: 2
formats: []

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
  builder: html

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs